name: Github Release PDF

on:
  push:
    branches:
      - main # 또는 기본 브랜치명
    tags:
      - 'v*' # v로 시작하는 태그에 대해서만 릴리스 생성
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - run: mdbook build

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-xetex fonts-noto-cjk

    - name: Create PDF directory
      run: mkdir -p pdf

    - name: Convert HTML to PDF using Pandoc
      run: |
        find book -name "*.html" -print0 | xargs -0 -I {} pandoc {} -o pdf/$(basename {} .html).pdf --pdf-engine=xelatex -V mainfont="Noto Sans CJK KR" -V sansfont="Noto Sans CJK KR" -V monofont="Noto Mono CJK KR"
        # Create a single combined PDF (optional, might need further refinement for table of contents etc.)
        # pandoc book/**/*.html -o pdf/output.pdf --pdf-engine=xelatex -V mainfont="Noto Sans CJK KR" -V sansfont="Noto Sans CJK KR" -V monofont="Noto Mono CJK KR" --toc

    - name: Upload PDF artifact (for pull requests and pushes to main)
      if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
      uses: actions/upload-artifact@v4
      with:
        name: pdf-output
        path: pdf/

    - name: Create Release and Upload PDF
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: pdf/*.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' # Deploy to GitHub Pages only on push to main
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book
